#!/usr/bin/env bash

set -e

main () {
  script_root=$(dirname $(realpath $0))

  local command="help" && [ ! -z "$1" ] && command=$1

  local command_args=${@:2}

  case $command in
    "help")
      _help $command_args
      ;;
    "init")
      _init $command_args
      ;;
    "launch")
      _launch $command_args
      ;;
  esac
}

_help () {
  echo "[HELP]"
  echo "$ landrop [COMMAND] [ARGS]"
  echo "List of available commands:"
  echo "- help # Displays this information"
  echo "- init LANDO_NAME # Initialises config files for drop and lando"
  echo "- launch # Starts lando and builds and installs via drop"
  return 0
}

_init () {
  local landrop_template && [ ! -z "$1" ] && landrop_template=$1 || landrop_template="default"
  local lando_name && [ ! -z "$2" ] && lando_name=$2 || lando_name=$landrop_template
  local template_dir=$script_root/templates/$landrop_template

  [ -d "$template_dir/landrop_template" ] && echo "[ERROR] provided template does not exist." && exit

  echo "Setting up lando & drop from $landrop_template"

  cp $template_dir/dot-lando.yml .lando.yml
  cp $template_dir/dot-drop.yml .drop.yml
  cp $template_dir/drop.yml drop.yml

  sed -i "s/LANDO_NAME/$lando_name/" .drop.yml .lando.yml

  echo "Installs drop... got it? ;)"
  [ ! -d .drop ] && rm -rf .drop && git clone git@github.com:pendashteh/drop.git .drop
}

_launch () {
  lando start
  lando drop drop.yml build
  lando drop drop.yml install -y
}

main ${@}
